_wandb:
    value:
        cli_version: 0.26.1
        e:
            usvhtmp2odlm7dfko62n9c93zonsjyhg:
                codePath: train_asil.py
                codePathLocal: train_asil.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "499534917632"
                        used: "441138458624"
                email: max107304@gmail.com
                executable: C:\Users\Dongha Lee\AppData\Local\Programs\Python\Python312\python.exe
                gpu: NVIDIA GeForce RTX 3070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Ti
                      uuid: GPU-c275236c-7a73-1e31-7b93-1dee69d90b8c
                host: DESKTOP-VDS44RT
                memory:
                    total: "34274660352"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Dongha Lee\Desktop\HFSP_Quality\train_asil.py
                python: CPython 3.12.6
                root: C:\Users\Dongha Lee\Desktop\HFSP_Quality
                startedAt: "2026-05-11T10:54:06.933413Z"
                writerId: usvhtmp2odlm7dfko62n9c93zonsjyhg
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.12.6
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
B:
    value: 5
P:
    value: 24
embedding_dim:
    value: 64
encoder_layer_num:
    value: 3
epoch_size:
    value: 50
eval_type:
    value: argmax
ff_hidden_dim:
    value: 128
head_num:
    value: 8
logit_clipping:
    value: 10
lr:
    value: 0.0001
lr_gamma:
    value: 0.1
lr_milestones:
    value:
        - 80
        - 90
mB:
    value: 5
machines:
    value:
        - 4
        - 4
        - 4
ms_hidden_dim:
    value: 16
ms_layer1_init:
    value: 0.7071067811865476
ms_layer2_init:
    value: 0.25
n_params:
    value: 228208
num_epochs:
    value: 100
num_jobs:
    value: 20
num_ops:
    value: 60
qkv_dim:
    value: 8
seed:
    value: 1
sqrt_embedding_dim:
    value: 8
sqrt_qkv_dim:
    value: 2.8284271247461903
time_high:
    value: 10
time_low:
    value: 2
weight_decay:
    value: 1e-06
