_wandb:
    value:
        cli_version: 0.26.1
        e:
            b47j4wwnsjec24rabc10sb9sv7yd14va:
                codePath: train_ASIL_with_quality.py
                codePathLocal: train_ASIL_with_quality.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "499431501824"
                        used: "359443615744"
                email: max107304@gmail.com
                executable: C:\Users\user\AppData\Local\Programs\Python\Python312\python.exe
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-8803da08-1a45-3ef4-49fd-4ad326b512fe
                host: DESKTOP-CF8LO69
                memory:
                    total: "68479098880"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\user\Desktop\Dongha\HFSP_Quality\train_ASIL_with_quality.py
                python: CPython 3.12.4
                root: C:\Users\user\Desktop\Dongha\HFSP_Quality
                startedAt: "2026-05-14T14:23:46.810382Z"
                writerId: b47j4wwnsjec24rabc10sb9sv7yd14va
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
                - 61
            "4": 3.12.4
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
B:
    value: 50
K:
    value: 10
M:
    value: 5
P:
    value: 24
embedding_dim:
    value: 256
encoder_layer_num:
    value: 3
epoch_size:
    value: 250
eval_type:
    value: argmax
ff_hidden_dim:
    value: 512
head_num:
    value: 16
hv_m_best:
    value: 30
hv_m_ref:
    value: 110
hv_q_best:
    value: 0.97
hv_q_ref:
    value: 0.9
logit_clipping:
    value: 5
lr:
    value: 0.0001
lr_gamma:
    value: 0.1
lr_milestones:
    value:
        - 80
        - 90
machines:
    value:
        - 5
        - 3
        - 7
        - 3
        - 5
        - 7
ms_hidden_dim:
    value: 16
ms_layer1_init:
    value: 0.7071067811865476
ms_layer2_init:
    value: 0.25
n_params:
    value: 5342816
num_epochs:
    value: 100
num_jobs:
    value: 15
num_ops:
    value: 90
qkv_dim:
    value: 16
seed:
    value: 1
sqrt_embedding_dim:
    value: 16
sqrt_qkv_dim:
    value: 4
time_high:
    value: 7
time_low:
    value: 3
weight_decay:
    value: 1e-06
